{% set name = "ahead_python" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Techtonique/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2b62c1946a28d13fb9c2094a31c0dfba386149f634bfa823c37bbd0fd99bc4a1

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - matplotlib-base
    - numpy >=1.14.0
    - scipy >=0.19.0
    - scikit-learn >=0.18.0
    - pandas >=1.3.5
    - tqdm >=4.48.1
    - rpy2 >=3.4.5
  run:
    - python
    - scipy >=0.19.0
    - scikit-learn >=0.18.0
    - matplotlib-base
    - pandas >=1.3.5
    - tqdm >=4.48.1
    - rpy2 >=3.4.5

test:
  imports: 
    - ahead

about:
  home: https://techtonique.github.io/ahead_python/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Univariate and multivariate time series forecasting, with uncertainty quantification
  description: Univariate and multivariate time series forecasting, with uncertainty quantification (Python & R).
  doc_url: https://techtonique.github.io/ahead_python/
  dev_url: https://github.com/Techtonique/ahead_python

extra:
  recipe-maintainers:
    - thierrymoudiki
